version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.13
    steps:
      - checkout
      - run: echo "A first hello"

  unit_test:
    docker:
      - image: golang:1.13.4
    steps:
      - checkout
      - run:
          name: Run unit tests
          command:
            sh bin/test

workflows:
  version: 2
  workflow:
    jobs:
    - build
    - unit_test
